services:

  javer-eureka-server:
    build:
      context: ./javer-eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      SERVER_PORT: 8761
      HOST: javer-eureka-service
    networks:
      - microservices-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://javer-eureka-server:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

#  db:
#    image: mysql:8.1.0
#    container_name: mysql-container
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_ALLOW_EMPTY_PASSWORD: true
#      MYSQL_DATABASE: customer_db
#    ports:
#      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#    networks:
#      - microservices-network
#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
#      interval: 30s
#      timeout: 10s
#      retries: 3

  javer-persistence-service:
    build:
      context: ./javer-persistence-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SERVER_PORT: 8000
      FEIGN_CLIENT_USERNAME: fuser
      FEIGN_CLIENT_PASSWORD: fpassword
      EUREKA_HOST: javer-eureka-server
      EUREKA_PORT: 8761
      MYSQL_HOST: javer-database-service-01.c5gakwa0kw9x.sa-east-1.rds.amazonaws.com
      MYSQL_PORT: 3306
      MYSQL_DB: javer_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - microservices-network
    depends_on:
#      - db
      - javer-eureka-server

  javer-proxy-service:
    build:
      context: ./javer-proxy-service
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    environment:
      SERVER_PORT: 8100
      FEIGN_CLIENT_USERNAME: fuser
      FEIGN_CLIENT_PASSWORD: fpassword
      EUREKA_HOST: javer-eureka-server
      EUREKA_PORT: 8761
    networks:
      - microservices-network
    depends_on:
      - javer-eureka-server
      - javer-persistence-service

  javer-gateway-service:
    build:
      context: ./javer-gateway-service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      SERVER_PORT: 9000
      EUREKA_PORT: 8761
      EUREKA_HOST: javer-eureka-server
      PERSISTENCE_HOST: javer-persistence-service
      PROXY_HOST: javer-proxy-service
    networks:
      - microservices-network
    depends_on:
      - javer-eureka-server
      - javer-persistence-service
      - javer-proxy-service

networks:
  microservices-network:
    driver: bridge

#volumes:
#  db_data:
