server:
  port: 8000

feign:
  client:
    username: fuser
    password: fpassword

eureka:
  client:
    serviceUrl:
      defaultZone: http://javer-eureka-server:8761/eureka/

spring:

  application:
    name: javer-persistence-service

  datasource:
    url: jdbc:mysql://db:3306/customer_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  flyway:
    url: jdbc:mysql://db:3306/
    schemas: customer_db
    user: root
    password: root
    locations: classpath:db/migration