spring:
  application:
    name: javer-eureka-server

server:
  port: ${SERVER_PORT:8761}

eureka:

  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false