server:
  port: ${SERVER_PORT:8100}

feign:
  client:
    username: ${FEIGN_CLIENT_USERNAME:fuser}
    password: ${FEIGN_CLIENT_PASSWORD:fpassword}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

spring:

  application:
    name: javer-proxy-service

#logging:
#  level:
#    root: INFO
#    org.springframework.web: DEBUG
#    com.bernmpdev.javerproxyservice: DEBUG